export const CHANGE_TOPLIST = 'musiclist/CHANGE_TOPLIST';
export const CHANGE_CURRENT_INDEX = 'musiclist/CHANGE_CURRENT_INDEX';
export const CHANGE_PLAYLIST = 'musiclist/CHANGE_PLAYLIST';
export const CHANGE_PLAYLIST_COMMENT = 'musiclist/CHANGE_PLAYLIST_COMMENT';