export const CHANGE_ALL_PLAYLIST = 'playlist/CHANGE_ALL_PLAYLIST';
export const CHANGE_TOTAL = 'playlist/CHANGE_TOTAL';
export const CHANGE_ALL_PLAYLIST_CATEGORY = 'playlist/CHANGE_ALL_PLAYLIST_CATEGORY';


